apiVersion: v1
kind: Service
metadata:
  name: tomcat
  labels:
    app: tomcat
spec:
  type: NodePort
  ports: 
    - port: 30123
      targetPort: 8080
      protocol: TCP
      name: http
  selector: 
    app: tomcat

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcat
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: bitnami/tomcat
        env:
        - name: TOMCAT_USERNAME
          value: tomcatuser
        - name: TOMCAT_PASSWORD
          value: qsxdr
        ports:
        - containerPort: 8080
          hostPort: 30123
          name: tomcat
        volumeMounts:
        - name: tomcat
          mountPath: /opt/bitnami/tomcat/webapps
      volumes:
        - name: tomcat
          persistentVolumeClaim:
            claimName: tomcat-claim1

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcat
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: bitnami/tomcat
        env:
        - name: TOMCAT_USERNAME
          value: tomcatuser
        - name: TOMCAT_PASSWORD
          value: qsxdr
        ports:
        - containerPort: 8080
          hostPort: 30123
          name: tomcat
        volumeMounts:
        - name: tomcat
          mountPath: /opt/bitnami/tomcat/webapps
      volumes:
        - name: tomcat
          persistentVolumeClaim:
            claimName: tomcat-claim2

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tomcat-claim1
  labels:
    app: tomcat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tomcat-claim2
  labels:
    app: tomcat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
