apiVersion: v1
kind: Service
metadata:
  name: mariatest-ss
  labels:
    app: mariatest-ss

spec:
  ports:
  - port: 3306
    name: mariaport
  clusterIP: None
  selector:
    app: mariatest-ss

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mariatest-ss
spec:
  serviceName: "mariatest-ss"
  replicas: 3
  template:
    metadata:
      labels:
        app: mariatest-ss
    spec:
      containers:
      - name: mariatest
        image: dexnov17/mariatest
        ports:
        - name: mysql
          containerPort: 3306
        env:
        # kubectl create secret generic mysql-pass --from-file=password.txt
        - name: MYSQL_ROOT_PASSWORD
          value: devops254
        - name: DISCOVERY_SERVICE
          value: 10.0.0.3:2379
        - name: XTRABACKUP_PASSWORD
          value: devops254
        - name: CLUSTER_NAME
          value: mariatest_cluster
        - name: MYSQL_DATABASE
          value: OMS
        - name: MYSQL_USER
          value: jenkins
        - name: MYSQL_PASSWORD
          value: devops254
        - name: HAPROXY_USER
          value: haproxy_check
        - name: HAPROXY_HOST_ADDR
          value: 172.30.86.5
        volumeMounts:
        - name: mysql-datadir
          mountPath: /var/lib/mysql:z
  volumeClaimTemplates:
  - metadata:
      name: mysql-datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
