apiVersion: v1
kind: Service
metadata:
  name: maria-ss
  labels:
    app: maria-ss
spec:
  ports:
  - port: 3306
    name: mysql
  clusterIP: None
  selector:
    app: maria-ss

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: galera-ss
spec:
  serviceName: "maria-ss"
  replicas: 3
  template:
    metadata:
      labels:
        app: maria-ss
    spec:
      containers:
      - name: maria
        image: severalnines/mariadb:10.1
        ports:
        - name: mysql
          containerPort: 3306
        env:
        # kubectl create secret generic mysql-pass --from-file=password.txt
        - name: MYSQL_ROOT_PASSWORD
          value: devops254
        - name: DISCOVERY_SERVICE
          value: 10.0.0.3:2379
        - name: XTRABACKUP_PASSWORD
          value: devops254
        - name: CLUSTER_NAME
          value: mariadb_galera_ss
        - name: MYSQL_DATABASE
          value: OMS_DB
        - name: MYSQL_USER
          value: jenkins
        - name: MYSQL_PASSWORD
          value: devops254
        readinessProbe:
          exec:
            command:
            - /healthcheck.sh
            - --readiness
          initialDelaySeconds: 120
          periodSeconds: 1
        livenessProbe:
          exec:
            command:
            - /healthcheck.sh
            - --liveness
          initialDelaySeconds: 120
          periodSeconds: 1
        volumeMounts:
        - name: mysql-datadir
          mountPath: /var/lib/mysql:z
  volumeClaimTemplates:
  - metadata:
      name: mysql-datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
