---
apiVersion: v1
kind: Service
metadata:
  name: nexus 
  labels:
    app: nexus
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 31081
  selector:
    app: nexus

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-local
  labels:
    type: local
    app: nexus
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data/nexus"  
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nexus-local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nexus
  labels:
    app: nexus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - name: nexus
        image: sonatype/nexus
        ports:
        - containerPort: 8081
        volumeMounts:
        - mountPath: "/tmp/data/nexus"
          name: nexusdp
  volumes:
  - name: nexusdp
    persistentVolumeClaim:
      claimName: nexus-local
---
