apiVersion: v1
kind: Service
metadata:
  name: tomcat-ss
  labels:
    app: tomcat-ss
spec:
  type: NodePort
  ports:
  - port: 30123
    targetPort: 8080
    protocol: TCP
    name: http
  clusterIP: None
  selector:
    app: tomcat-ss

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: tomcat-ss
spec:
  serviceName: "tomcat-ss"
  replicas: 3
  template:
    metadata:
      labels:
        app: tomcat-ss
    spec:
      containers:
      - name: tomcat
        image: bitnami/tomcat
        ports:
        - name: mysql
          containerPort: 3306
          hostPort: 30123
        env:
        - name: TOMCAT_USERNAME
          value: tomcatuser
        - name: TOMCAT_PASSWORD
          value: qsxdr
        volumeMounts:
        - name: tomcat-datadir
          mountPath: /bitnami/tomcat/data:z
  volumeClaimTemplates:
  - metadata:
      name: tomcat-datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
