---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-tomcat-0
  labels:
    app: tomcat-ss
    podindex: "0"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3Gi
  hostPath:
    path: /data/pods/tomcat-0/datadir
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-tomcat-1
  labels:
    app: tomcat-ss
    podindex: "1"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3Gi
  hostPath:
    path: /data/pods/tomcat-1/datadir
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-tomcat-2
  labels:
    app: tomcat-ss
    podindex: "2"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3Gi
  hostPath:
    path: /data/pods/tomcat-2/datadir
